/**
 * Bulk-mail detection from RFC header fields.
 *
 * Lets a mailbox be triaged (newsletter vs automated notification vs personal
 * mail) from headers alone — deterministic, and cheap enough to run over a
 * whole page of results in a single IMAP fetch.
 */

import type { BulkKind, BulkSignal } from '../types/index.js';

export { default as parseHeaderBlock } from './headers.js';

/**
 * Header fields worth fetching for classification. Kept deliberately short:
 * every field here is pulled for every message in a listing.
 */
export const BULK_HEADER_FIELDS = [
  'list-unsubscribe',
  'list-unsubscribe-post',
  'list-id',
  'precedence',
  'auto-submitted',
];

/** `Precedence:` values that mark mail as machine-originated rather than a list. */
const AUTOMATED_PRECEDENCE = new Set(['bulk', 'junk', 'auto_reply']);

/**
 * Parse a raw header block into lowercased keys.
 *
 * Unfolds continuation lines per RFC 5322 §2.2.3 — a folded `List-Unsubscribe`
 * carrying both an https and a mailto URI is common, and naive line splitting
 * silently truncates it.
 */
/** Pick the most actionable unsubscribe URI, preferring https over mailto. */
function pickUnsubscribeUri(value: string): string | undefined {
  const uris = [...value.matchAll(/<([^>]+)>/g)].map((m) => m[1]?.trim()).filter(Boolean);
  const candidates = uris.length > 0 ? uris : [value.trim()];
  return (
    candidates.find((u) => u?.startsWith('https://')) ??
    candidates.find((u) => u?.startsWith('http://')) ??
    candidates.find((u) => u?.startsWith('mailto:')) ??
    candidates[0]
  );
}

/** Strip the angle brackets List-Id wraps its identifier in. */
function cleanListId(value: string): string {
  const bracketed = /<([^>]+)>/.exec(value);
  return (bracketed?.[1] ?? value).trim();
}

/**
 * Classify a message from its headers.
 *
 * Returns `undefined` for ordinary person-to-person mail, so callers can stay
 * silent rather than labelling every message.
 */
export function classifyBulk(headers: Record<string, string>): BulkSignal | undefined {
  const unsubscribeRaw = headers['list-unsubscribe'];
  const listIdRaw = headers['list-id'];
  const precedence = headers.precedence?.trim().toLowerCase();
  const autoSubmitted = headers['auto-submitted']?.trim().toLowerCase();

  // RFC 3834: anything but "no" means the message was generated by software.
  const isAutomated =
    (autoSubmitted !== undefined && autoSubmitted !== 'no') ||
    (precedence !== undefined && AUTOMATED_PRECEDENCE.has(precedence));

  const isList = unsubscribeRaw !== undefined || listIdRaw !== undefined || precedence === 'list';

  if (!isList && !isAutomated) {
    return undefined;
  }

  // A list wins over the automated marker: bulk senders routinely set both, and
  // "newsletter" is the more actionable of the two for triage.
  const kind: BulkKind = isList ? 'newsletter' : 'automated';

  return {
    kind,
    listId: listIdRaw ? cleanListId(listIdRaw) : undefined,
    unsubscribe: unsubscribeRaw ? pickUnsubscribeUri(unsubscribeRaw) : undefined,
    // RFC 8058: presence of List-Unsubscribe-Post means one-click works.
    oneClick: headers['list-unsubscribe-post'] !== undefined,
  };
}

/**
 * Render a bulk signal as one compact line, or an empty string for personal
 * mail. Compact by design: it repeats for every item of a listing.
 */
export function formatBulk(bulk: BulkSignal | undefined): string {
  if (!bulk) {
    return '';
  }
  const marker = bulk.kind === 'newsletter' ? '📰 newsletter' : '🤖 automated';
  const listId = bulk.listId ? ` (${bulk.listId})` : '';
  const unsubscribe = bulk.unsubscribe ? ` · unsub${bulk.oneClick ? ' 1-click' : ''}` : '';
  return `${marker}${listId}${unsubscribe}`;
}
